### ISSUE TITLE
Resources or rooms are not all created

### ISSUE THREAD

**Issue by TiDjY35** [nextcloud/calendar_resource_management#63] opened 2022-09-06 12:10 UTC
### Steps to reproduce

Hello, I created the rooms from the command line

NC version 24 in docker

docker exec --user 33 TOURMALINE_nextcloud_app php /var/www/html/occ calendar-resource:building:create "Centre hospitalier" "31 bd Salvador Allende, 44800 ST HERBLAIN, FRANCE" ""
docker exec --user 33 TOURMALINE_nextcloud_app php /var/www/html/occ calendar-resource:story:create 2 "1er étage"

docker exec --user 33 TOURMALINE_nextcloud_app php /var/www/html/occ calendar-resource:room:create 2 "SalleD102" "Salle D102" "salled102@prmt44.fr" 0 "Modérateurs" 25 102 0 1 1 1 1 1
docker exec --user 33 TOURMALINE_nextcloud_app php /var/www/html/occ calendar-resource:room:create 2 "SalleD106" "Salle D106" "salled106@prmt44.fr" 0 "Modérateurs" 12 106 0 1 1 1 1 1
docker exec --user 33 TOURMALINE_nextcloud_app php /var/www/html/occ calendar-resource:room:create 2 "Salle2PG" "Salle 2PG à l’ESRP" "salle2pg@prmt44.fr" 0 "Modérateurs" 15 2 0 1 0 1 1 1
docker exec --user 33 TOURMALINE_nextcloud_app php /var/www/html/occ calendar-resource:room:create 2 "salleamangerdir" "Salle à manger direction" "salleamanger@prmt44.fr" 0 "Modérateurs" 20 0

docker exec --user 33 TOURMALINE_nextcloud_app php /var/www/html/occ calendar-resource:vehicle:create "308-FG-448-QZ" 2 "308 auto FG-448-QZ" "FG-448-QZ@prmt44.fr" "Modérateurs" "BERLINE" "PEUGEOT" "308 BOITE AUTOMATIQUE" 0 0 5

docker exec --user 33 TOURMALINE_nextcloud_app php /var/www/html/occ calendar-resource:vehicle:create "BE-387-BA" 2 "Mégane Grise BE-387-BA" "BE-387-BA@prmt44.fr" "Modérateurs" "BERLINE" "RENAULT" "MEGANE" 0 0 5

docker exec --user 33 TOURMALINE_nextcloud_app php /var/www/html/occ calendar-resource:vehicle:create "CN-127-VP" 2 "Kangoo CN-127-VP" "CN-127-VP@prmt44.fr" "Modérateurs" "BERLINE" "RENAULT" "KANGOO" 0 0 5

docker exec --user 33 TOURMALINE_nextcloud_app php /var/www/html/occ calendar-resource:vehicle:create "DK-638-EG" 2 "C3 DK-638-EG" "DK-638-EG@prmt44.fr" "Modérateurs" "BERLINE" "CITROEN" "C3" 0 0 5

docker exec --user 33 TOURMALINE_nextcloud_app php /var/www/html/occ calendar-resource:resource:create "Vidéoprojecteur" 2 "Vidéoprojecteur" "Vidéoprojecteur@prmt44.fr" 0

and examples

php occ calendar-resource:building:create "SpaceZ office Berlin" "Testweg 23, 12345 Berlin, Germany" ""
php occ calendar-resource:story:create 1 "2nd floor"
php occ calendar-resource:room:create 1 "berlin_main_office" "Shared office" "room.berlin.main@spacexyz.com" 0 "demouser" 25 201

### Expected behavior

All resource view on calendar app and database

### Actual behavior

And not all resources have been created in the database

![image](https://user-images.githubusercontent.com/4006867/188629859-e3939d58-a41e-41d9-bbd7-2922bc3535f2.png)

but OK in list

![image](https://user-images.githubusercontent.com/4006867/188630906-8b0ad826-71b4-4002-87ca-dae8fa2b9cdb.png)

### App version

0.2.0

**Comment by digitalfox** [comment] 2022-09-11 18:22
same issue with nextcloud 23.0.9 and Calendar Resource Management 0.3.1 installed via the app store.

**Comment by fixed77** [comment] 2022-09-13 14:15
same behavior on NC22

**Comment by unteem** [comment] 2022-10-10 13:17
looks like a duplicate of https://github.com/nextcloud/calendar_resource_management/issues/51

**Comment by pierreozoux** [comment] 2022-10-17 15:31
Closing in favor of https://github.com/nextcloud/calendar_resource_management/issues/51

**Closed by pierreozoux** 2022-10-17 15:31 UTC
Labels: bug, 0. to triage
