### ISSUE TITLE
Show ressources as calendar

### ISSUE THREAD

**Issue by seebag** [nextcloud/calendar_resource_management#105] opened 2024-01-19 21:12 UTC
### Describe the solution you'd like

It would be nice if we could show the calendar of a specific ressource. 
The idea is to know when the ressource is reserved and by whom.

**Comment by MaBurn** [comment] 2024-01-29 19:49
would be nice to have this.

**Comment by ChristophWurst** [comment] 2024-01-29 19:51
Duplicate of https://github.com/nextcloud/calendar/issues/3185

**Closed by ChristophWurst** 2024-01-29 19:51 UTC
Labels: enhancement, 0. to triage
